// Code generated by protoc-gen-go. DO NOT EDIT.
// source: applogic/applogic.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	applogic/applogic.proto

It has these top-level messages:
	SayRequest
	SayReply
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type SayRequest struct {
	Text string `protobuf:"bytes,1,opt,name=Text" json:"Text,omitempty"`
}

func (m *SayRequest) Reset()                    { *m = SayRequest{} }
func (m *SayRequest) String() string            { return proto1.CompactTextString(m) }
func (*SayRequest) ProtoMessage()               {}
func (*SayRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SayRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type SayReply struct {
	Flag string `protobuf:"bytes,1,opt,name=Flag" json:"Flag,omitempty"`
}

func (m *SayReply) Reset()                    { *m = SayReply{} }
func (m *SayReply) String() string            { return proto1.CompactTextString(m) }
func (*SayReply) ProtoMessage()               {}
func (*SayReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SayReply) GetFlag() string {
	if m != nil {
		return m.Flag
	}
	return ""
}

func init() {
	proto1.RegisterType((*SayRequest)(nil), "proto.SayRequest")
	proto1.RegisterType((*SayReply)(nil), "proto.SayReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Applogic service

type ApplogicClient interface {
	Say(ctx context.Context, in *SayRequest, opts ...grpc.CallOption) (*SayReply, error)
}

type applogicClient struct {
	cc *grpc.ClientConn
}

// iogo do
// func NewApplogicClient(cc *grpc.ClientConn) ApplogicClient {
// 	return &applogicClient{cc}
// }

func (c *applogicClient) Say(ctx context.Context, in *SayRequest, opts ...grpc.CallOption) (*SayReply, error) {
	out := new(SayReply)
	err := grpc.Invoke(ctx, "/proto.Applogic/Say", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Applogic service

type ApplogicServer interface {
	Say(context.Context, *SayRequest) (*SayReply, error)
}

// iogo do
// func RegisterApplogicServer(s *grpc.Server, srv ApplogicServer) {
// 	s.RegisterService(&_Applogic_serviceDesc, srv)
// }

func _Applogic_Say_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplogicServer).Say(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Applogic/Say",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplogicServer).Say(ctx, req.(*SayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Applogic_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Applogic",
	HandlerType: (*ApplogicServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Say",
			Handler:    _Applogic_Say_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "applogic/applogic.proto",
}

func init() { proto1.RegisterFile("applogic/applogic.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 139 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4f, 0x2c, 0x28, 0xc8,
	0xc9, 0x4f, 0xcf, 0x4c, 0xd6, 0x87, 0x31, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x58, 0xc1,
	0x94, 0x92, 0x02, 0x17, 0x57, 0x70, 0x62, 0x65, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x90,
	0x10, 0x17, 0x4b, 0x48, 0x6a, 0x45, 0x89, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x98, 0xad,
	0x24, 0xc7, 0xc5, 0x01, 0x56, 0x51, 0x90, 0x53, 0x09, 0x92, 0x77, 0xcb, 0x49, 0x4c, 0x87, 0xc9,
	0x83, 0xd8, 0x46, 0xe6, 0x5c, 0x1c, 0x8e, 0x50, 0xa3, 0x85, 0xb4, 0xb9, 0x98, 0x83, 0x13, 0x2b,
	0x85, 0x04, 0x21, 0x76, 0xe8, 0x21, 0x4c, 0x96, 0xe2, 0x47, 0x16, 0x2a, 0xc8, 0xa9, 0x54, 0x62,
	0x70, 0x62, 0x5b, 0xc4, 0xc4, 0xec, 0xe1, 0x13, 0x9e, 0xc4, 0x06, 0x96, 0x31, 0x06, 0x04, 0x00,
	0x00, 0xff, 0xff, 0xcc, 0x4b, 0x81, 0xee, 0xab, 0x00, 0x00, 0x00,
}
